import { createElement } from 'lwc';
import SampleComponent from 'c/sampleComponent';

describe('c-sample-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-sample-component', {
            is: SampleComponent
        });
        document.body.appendChild(element);

        return Promise.resolve().then(() => {          
                        const formattedTexts = element.shadowRoot.querySelectorAll('lightning-formatted-text');
                        expect(formattedTexts[1].value).toBe('FNAME LNAME');
                    });
            

        
    });
});